const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.ERA_ELEVEN_PLAYWRIGHT || 'playwright');
if (!process.env.ERA_ELEVEN_TEST_OUTPUT) throw new Error('Set ERA_ELEVEN_TEST_OUTPUT to your project work folder.');
const output=path.resolve(process.env.ERA_ELEVEN_TEST_OUTPUT);fs.mkdirSync(output,{recursive:true});
const base=process.env.ERA_ELEVEN_URL||'http://127.0.0.1:8765';let browser;const checks=[],errors=[];
async function click(p,s){await p.locator(s).click();await p.waitForFunction(()=>document.body.getAttribute('aria-busy')!=='true');assert.equal(await p.locator('#error').isVisible(),false,await p.locator('#error').textContent());}
async function state(p){return p.evaluate(async()=>{const s=JSON.parse(localStorage.getItem('era-eleven-v2'));return(await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:s.token})})).json();});}
async function run(){browser=await chromium.launch({headless:true});const p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>document.body.getAttribute('aria-busy')!=='true');await click(p,'[data-mode="gauntlet"]');await p.locator('#draft-seed').fill('17');await click(p,'#new-game');for(let i=0;i<5;i++)await click(p,'#spin');
  await click(p,'#advance');let s=await state(p);let patience=s.progress.patience;
  await p.locator('#management-actions button').filter({hasText:'Develop pressing'}).click();await p.waitForFunction(()=>document.body.getAttribute('aria-busy')!=='true');s=await state(p);assert.equal(s.progress.badges,1);assert.equal(s.progress.patience,patience-1);assert.match(await p.locator('#competition-progress').textContent(),/Badges: 1/);checks.push('Pressing development spends patience and displays its saved badge');
  await click(p,'#advance');s=await state(p);patience=s.progress.patience;await p.locator('#management-actions button').filter({hasText:'Develop era'}).click();await p.waitForFunction(()=>document.body.getAttribute('aria-busy')!=='true');s=await state(p);assert.equal(s.progress.era_upgrades,1);assert.equal(s.progress.patience,patience-1);checks.push('Era adaptation spends patience and displays its saved upgrade');
  await click(p,'#advance');s=await state(p);const before=s.squad.map(x=>x.identity);patience=s.progress.patience;let pair;
  for(const out of s.bench){for(const incoming of s.progress.free_agents){if(incoming.tier==='B'&&out.positions.some(pos=>incoming.positions.includes(pos))){pair=[out,incoming];break;}}if(pair)break;}
  assert.ok(pair,'At least one same-position affordable offered signing');await p.locator('[data-free-agent-out]').selectOption(pair[0].id);await p.locator('[data-free-agent-in]').selectOption(pair[1].id);await p.locator('#management-actions button').filter({hasText:'Replace a substitute'}).click();await p.waitForFunction(()=>document.body.getAttribute('aria-busy')!=='true');assert.equal(await p.locator('#error').isVisible(),false,await p.locator('#error').textContent());s=await state(p);assert.equal(s.count,15);assert.equal(new Set(s.squad.map(x=>x.identity)).size,15);assert.ok(s.squad.some(x=>x.id===pair[1].id));assert.ok(!s.squad.some(x=>x.id===pair[0].id));assert.equal(s.progress.patience,patience-1);assert.equal(s.progress.needs_management,false);await p.reload();await p.waitForFunction(()=>document.body.getAttribute('aria-busy')!=='true');s=await state(p);assert.equal(s.progress.badges,1);assert.equal(s.progress.era_upgrades,1);assert.ok(s.squad.some(x=>x.id===pair[1].id));checks.push('One-for-one signing and both development choices survive reload');assert.deepEqual(errors,[]);}
async function salaryRoom(){
  const p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>document.body.getAttribute('aria-busy')!=='true');await click(p,'[data-mode="head-to-head"]');assert.equal(await p.locator('#variant-control').isVisible(),true);await p.locator('#draft-variant').selectOption('salary-cap');await click(p,'#room-local');
  for(let i=0;i<10;i++){await click(p,'#spin');assert.equal(await p.locator('#salary-budget').isVisible(),true);if(await p.locator('#handover').isVisible())await click(p,'#handover-confirm');}
  const view=await p.evaluate(async()=>{const s=JSON.parse(localStorage.getItem('era-eleven-v2'));return(await fetch('/api/room/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room:s.room.room,credential:s.room.local_credentials[s.room.seat]})})).json();});assert.equal(view.variant,'salary-cap');for(const seat of view.seats){assert.equal(seat.count,15);assert.deepEqual(seat.salary.tiers,{S:2,A:4,B:9});assert.ok(seat.salary.spent<=seat.salary.cap);}
  await click(p,'#room-ready');if(await p.locator('#handover').isVisible())await click(p,'#handover-confirm');await click(p,'#room-ready');assert.equal(await p.locator('#room-result').isVisible(),true);checks.push('Local two-human salary draft displays budgets, enforces both quotas, and plays a shared match');assert.deepEqual(errors,[]);await p.close();
}
run().then(salaryRoom).then(async()=>{fs.writeFileSync(path.join(output,'management-review-results.json'),JSON.stringify({base,checks,errors,passed:true},null,2));await browser.close();}).catch(async e=>{fs.writeFileSync(path.join(output,'management-review-results.json'),JSON.stringify({base,checks,errors,passed:false,failure:e.stack},null,2));if(browser)await browser.close();process.stderr.write(e.stack+'\n');process.exitCode=1;});
