/* Checks saved presentation controls and profile switching without writing private backups. */
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const {chromium} = require(process.env.ERA_ELEVEN_PLAYWRIGHT || 'playwright');
if (!process.env.ERA_ELEVEN_TEST_OUTPUT) throw new Error('Set ERA_ELEVEN_TEST_OUTPUT to your project work folder.');
const output=path.resolve(process.env.ERA_ELEVEN_TEST_OUTPUT);fs.mkdirSync(output,{recursive:true});
const base = process.env.ERA_ELEVEN_URL || 'http://127.0.0.1:8765';
const checks=[],errors=[];let browser;
const check=(name,details)=>{checks.push({name,details,passed:true});process.stdout.write(name+'\n');};
async function settle(page){await page.waitForFunction(()=>document.body.getAttribute('aria-busy')!=='true',undefined,{timeout:90000});}
async function click(page,selector){if(selector==='[data-career="true"]'&&!await page.locator(selector).isVisible()){await page.locator('[data-page="play"]').click();await settle(page);}if(selector==='#new-game'&&await page.locator('#career-panel').isVisible()){await page.locator('[data-mode="solo"]').click();await settle(page);}await page.locator(selector).click();await settle(page);assert.equal(await page.locator('#error').isVisible(),false,await page.locator('#error').textContent());}
async function boot(context){const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.goto(base,{waitUntil:'domcontentloaded'});await settle(page);assert.equal(await page.locator('#connection').textContent(),'SERVER CONNECTED');return page;}
async function state(page){return page.evaluate(async()=>{const s=JSON.parse(localStorage.getItem('era-eleven-v2'));return(await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:s.token})})).json();});}
async function preferences(page,settings){
  await click(page,'[data-page="settings"]');
  const ids={era_fx:'era-fx',screen_fx:'screen-fx',reduce_motion:'reduce-motion',sound:'sound',auto_subs:'pref-auto-subs',theme:'theme',speed:'speed',appearance:'appearance',backdrop:'backdrop',roster_sort:'roster-sort',lineup_view:'lineup-view'};
  for(const[key,value]of Object.entries(settings)){const control=page.locator('#'+(ids[key]||key));if(typeof value==='boolean')await control.setChecked(value);else if(key==='volume')await control.evaluate((element,value)=>{element.value=String(value);element.dispatchEvent(new Event('input',{bubbles:true}));},value);else await control.selectOption(value);}
  await click(page,'#preferences button');
}
async function backup(page){
  await click(page,'[data-page="settings"]');
  await page.evaluate(()=>{if(window.__backupHook)return;window.__backupHook=true;const native=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){if(this.download==='Era Eleven private profile access.json'){window.__privateBackup=fetch(this.href).then(response=>response.text());return;}return native.call(this);};});
  await click(page,'#profile-export');return page.evaluate(()=>window.__privateBackup);
}
async function restore(page,text){await click(page,'[data-page="settings"]');await page.locator('#profile-file').setInputFiles({name:'Private profile access.json',mimeType:'application/json',buffer:Buffer.from(text)});await click(page,'#profile-import');}
async function run(){
  browser=await chromium.launch({headless:true});const aContext=await browser.newContext({viewport:{width:1440,height:1100}}),bContext=await browser.newContext();const a=await boot(aContext),b=await boot(bContext);
  for(const next of ['play','challenges','clubhouse','settings']){await click(a,`[data-page="${next}"]`);assert.equal(await a.locator('#page-'+next).isVisible(),true);assert.equal(await a.locator('.page:visible').count(),1);}
  await click(a,'#help-btn');assert.equal(await a.locator('#help').isVisible(),true);await click(a,'#help-done');assert.equal(await a.locator('#help').isVisible(),false);check('Every main navigation page and the help completion control work');
  const chosen={era_fx:false,screen_fx:false,reduce_motion:true,sound:true,volume:.25,theme:'night',speed:'instant',appearance:'light',backdrop:'stars',roster_sort:'position',lineup_view:'rows',auto_subs:false};await preferences(a,chosen);await a.reload();await settle(a);
  const applied=await a.evaluate(async()=>{const saved=JSON.parse(localStorage.getItem('era-eleven-v2'));const p=await(await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:saved.profile})})).json();return{settings:p.settings,body:{theme:document.body.dataset.theme,appearance:document.body.dataset.appearance,backdrop:document.body.dataset.backdrop,speed:document.body.dataset.speed,lineup:document.body.dataset.lineupView,fx:document.body.classList.contains('era-fx'),motion:document.body.classList.contains('reduce-motion')}};});
  for(const[key,value]of Object.entries(chosen))assert.equal(applied.settings[key],value,key);assert.deepEqual(applied.body,{theme:'night',appearance:'light',backdrop:'stars',speed:'instant',lineup:'rows',fx:false,motion:true});assert.equal(await a.locator('#volume-value').textContent(),'25%');check(`All ${Object.keys(chosen).length} presentation preferences save and restore their actual values`,chosen);
  await click(a,'[data-page="play"]');await a.locator('#draft-seed').fill('42');await click(a,'#new-game');assert.equal((await state(a)).config.auto_subs,false);
  await a.evaluate(()=>{const native=BaseAudioContext.prototype.createGain;BaseAudioContext.prototype.createGain=function(){const gain=native.call(this),set=gain.gain.setValueAtTime.bind(gain.gain);gain.gain.setValueAtTime=function(value,time){window.__revealGain=value;return set(value,time);};return gain;};});await click(a,'#spin');assert.equal(await a.evaluate(()=>window.__revealGain),.0125);check('Saved substitution preference reaches the engine and volume scales the real reveal audio graph');
  for(let i=0;i<4;i++)await click(a,'#spin');await click(a,'#play');
  await a.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('Clipboard unavailable in verification');}}});});await click(a,'#share');assert.equal(await a.locator('#share-dialog').isVisible(),true);const shared=await a.locator('#share-copy-text').inputValue();const access=await a.evaluate(()=>{const s=JSON.parse(localStorage.getItem('era-eleven-v2'));return{profile:s.profile,token:s.token};});assert.ok(shared.includes('Era Eleven'));assert.equal(shared.includes(access.profile),false);assert.equal(shared.includes(access.token),false);await click(a,'#share-dialog-close');check('Result sharing falls back to selectable text and excludes private access');
  await click(a,'[data-career="true"]');await a.locator('#career-name').fill('Restored career');await click(a,'#career-create button');const aBackup=await backup(a);
  await b.locator('#draft-seed').fill('19');await click(b,'#new-game');await click(b,'#spin');const bRun=(await state(b)).token;await click(b,'[data-career="true"]');await b.locator('#career-name').fill('Previous profile career');await click(b,'#career-create button');const bBackup=await backup(b);
  await restore(b,aBackup);const moved=await b.evaluate(()=>JSON.parse(localStorage.getItem('era-eleven-v2')));assert.equal(moved.profile,JSON.parse(aBackup).profile);assert.equal(moved.careerToken,JSON.parse(aBackup).careerToken);assert.equal(moved.token,null);await click(b,'[data-career="true"]');assert.equal(await b.locator('#career-player').textContent(),'Restored career · ST');check('Profile backup restores the authoritative collection and correct saved career in another browser');
  await restore(b,bBackup);const returned=await b.evaluate(()=>JSON.parse(localStorage.getItem('era-eleven-v2')));assert.equal(returned.profile,JSON.parse(bBackup).profile);assert.equal(returned.token,bRun);await click(b,'[data-page="play"]');await click(b,'#resume-run');assert.equal((await state(b)).count,3);check('Switching back to the previous profile preserves its earlier draft access');
  await preferences(a,{era_fx:true,screen_fx:true,reduce_motion:false,sound:false,volume:.5,theme:'stadium',speed:'normal',appearance:'dark',backdrop:'stadium',roster_sort:'rating',lineup_view:'pitch',auto_subs:true});await click(a,'[data-page="play"]');await click(a,'#new-game');for(let i=0;i<5;i++)await click(a,'#spin');await click(a,'#play');await a.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});await a.screenshot({path:path.join(output,'desktop-gameplay.png'),fullPage:true});await a.screenshot({path:path.join(output,'desktop-menu.png'),fullPage:false});check('Original dark desktop gameplay and menu previews captured from the live UI');
  assert.deepEqual(errors,[]);check('Presentation and profile controls produce no browser JavaScript exceptions');
}
run().then(async()=>{fs.writeFileSync(path.join(output,'presentation-review-results.json'),JSON.stringify({base,checks,errors,passed:true},null,2));await browser.close();}).catch(async error=>{fs.writeFileSync(path.join(output,'presentation-review-results.json'),JSON.stringify({base,checks,errors,passed:false,failure:error.stack},null,2));process.stderr.write(error.stack+'\n');if(browser)await browser.close();process.exitCode=1;});
