'use strict';
const $=id=>document.getElementById(id);
let token=null,game=null,era='All eras',busy=false;
const descriptions={'All eras':'All generations share one pitch.','Legends':'Base ICONs and HEROes, including pre-1990 classics.','1990s':'A career-era pool using reconstructed ICON and HERO ratings.','2000s':'A career-era pool using reconstructed ICON and HERO ratings.','2010s':'Published FIFA 18 career ratings, from the 2017 snapshot.','2020s':'Published FC 24 career ratings, from the 2023 snapshot.'};
const hints={'All eras':'THE FULL POOL','Legends':'CLASSICS & ICONS','1990s':'THE ARTISTS','2000s':'THE GOLDEN YEARS','2010s':'THE RIVALRY','2020s':'THE NEW GUARD'};
async function api(path,data){const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,token})});const out=await response.json();if(!response.ok)throw new Error(out.error||'Request failed');return out;}
async function action(fn){if(busy)return;busy=true;document.querySelectorAll('button[data-action],#spin,#new-game,#swap,#play,#series,#season').forEach(b=>b.disabled=true);try{await fn();$('status').textContent='';}catch(e){$('status').textContent=e.message;}finally{busy=false;updateButtons();}}
function updateButtons(){for(const id of ['new-game','random-seed'])$(id).disabled=busy;$('spin').disabled=busy||!!game?.complete;for(const id of ['swap','play','series','season','export'])$(id).disabled=busy||!game?.complete;document.querySelectorAll('.era-btn').forEach(b=>b.disabled=busy);}
function render(g){game=g;$('manager-name').textContent=g.manager.name;$('manager-style').textContent=g.manager.style;$('formation-label').textContent=g.formation;$('count').innerHTML=String(g.count).padStart(2,'0')+' <span>/ 15</span>';$('progress').innerHTML=Array.from({length:5},(_,i)=>'<span class="'+(i<g.spins?'filled':'')+'"></span>').join('');$('spin-hint').textContent=g.complete?'Squad complete · Pick your eleven':`Spin ${g.spins+1} of 5 · Every card joins your squad`;$('spin').innerHTML=g.complete?'SQUAD COMPLETE ✓':'SPIN · 3 PLAYERS <span>↻</span>';if(g.cards.length)$('cards').innerHTML='<div class="cards">'+g.cards.join('')+'</div>';else $('cards').innerHTML='<div class="cards">'+Array.from({length:3},()=>'<div class="empty-card"><span>?</span><small>THE NEXT LEGEND</small></div>').join('')+'</div>';$('squad-list').replaceChildren(...g.squad.map(p=>{const row=document.createElement('div');row.className='squad-row';const name=document.createElement('span');name.textContent=p.name;const value=document.createElement('span');value.textContent=p.overall+' '+p.positions.join('/');row.append(name,value);return row;}));$('lineup-section').hidden=!g.complete;$('match-section').hidden=!g.complete;if(g.complete){$('lineup').innerHTML=g.team_html;$('slot').replaceChildren(...g.starters.map(s=>new Option(s.slot+' · '+s.name,s.index)));$('bench').replaceChildren(...g.bench.map(p=>new Option(p.name+' · '+p.positions.join('/'),p.id)));}updateButtons();}
function newGame(){return action(async()=>{const seed=Number($('draft-seed').value);if(!Number.isInteger(seed)||seed<0||seed>2147483647)throw new Error('Choose a whole draft seed from 0 to 2147483647.');const g=await api('new',{era,seed,config:{chemistry_weight:Number($('chemistry').value),tactical_weight:Number($('tactics').value),auto_subs:$('auto-subs').checked}});token=g.token;render(g);$('match-result').hidden=true;});}
$('new-game').addEventListener('click',newGame);
$('random-seed').addEventListener('click',()=>{if(busy)return;$('draft-seed').value=crypto.getRandomValues(new Uint32Array(1))[0]%2147483647;newGame();});
$('spin').addEventListener('click',()=>action(async()=>{$('cards').classList.add('spinning');$('spin').textContent='SPINNING…';try{const [g]=await Promise.all([api('spin',{}),new Promise(r=>setTimeout(r,700))]);render(g);}finally{$('cards').classList.remove('spinning');if(game)render(game);}}));
$('swap').addEventListener('click',()=>action(async()=>{render(await api('swap',{slot:Number($('slot').value),bench_id:$('bench').value}));$('match-result').hidden=true;}));
function matchSeed(){const seed=Number($('match-seed').value);if(!Number.isSafeInteger(seed)||seed<0)throw new Error('Match seed must be a nonnegative whole number.');return seed;}
$('play').addEventListener('click',()=>action(async()=>{const r=await api('match',{seed:matchSeed()});$('match-result').innerHTML='<p class="caps small muted">Your XI vs '+r.opponent+'</p>'+r.html;$('match-result').hidden=false;}));
$('series').addEventListener('click',()=>action(async()=>{const r=await api('series',{seed:matchSeed(),n:2000});$('match-result').innerHTML='<h2>2,000 MATCHES</h2>'+Object.entries(r.probabilities).map(([key,p])=>'<div class="metric"><span>'+key.toUpperCase()+'</span><b>'+(p*100).toFixed(1)+'%</b></div><div class="bar"><i style="width:'+p*100+'%"></i></div>').join('')+'<p class="small muted">Same teams and model. Sampling intervals and sensitivity analysis are available in the notebook. Model uncertainty is not measured.</p>';$('match-result').hidden=false;}));
$('season').addEventListener('click',()=>action(async()=>{const r=await api('season',{seed:matchSeed()});$('match-result').innerHTML='<h2>38-MATCH GAUNTLET</h2><div class="score">'+r.wins+'–'+r.draws+'–'+r.losses+'</div><div class="metric"><span>Points</span><b>'+r.points+'</b></div><div class="metric"><span>Longest unbeaten run</span><b>'+r.best_unbeaten+'</b></div><p class="small muted">'+r.label+'</p><div class="timeline">'+r.matches.map(m=>'<div class="event">'+m.match+' · '+m.outcome+' · '+m.goals_for+' : '+m.goals_against+'</div>').join('')+'</div>';$('match-result').hidden=false;}));
$('export').addEventListener('click',()=>action(async()=>{const r=await api('export',{});const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`Era Eleven ${r.era} seed ${r.seed}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}));
$('help-btn').addEventListener('click',()=>$('help').showModal());$('close-help').addEventListener('click',()=>$('help').close());
(async()=>{try{const meta=await(await fetch('/api/meta')).json();$('pool-size').textContent=meta.players+' published player cards';$('eras').replaceChildren(...meta.eras.map(name=>{const b=document.createElement('button');b.className='era-btn'+(name===era?' active':'');b.innerHTML=name.toUpperCase()+'<small>'+hints[name]+'</small>';b.setAttribute('aria-pressed',name===era?'true':'false');b.addEventListener('click',()=>{if(busy)return;era=name;$('era-note').textContent=descriptions[name];document.querySelectorAll('.era-btn').forEach(el=>{const yes=el===b;el.classList.toggle('active',yes);el.setAttribute('aria-pressed',String(yes));});newGame();});return b;}));await newGame();}catch(e){$('status').textContent=e.message;}})();
